version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - platform: Any CPU
      configuration: Debug
    - platform: Any CPU
      configuration: Release
matrix:
  fast_finish: false
build:
  parallel: true
  verbosity: normal
artifacts:
- path: shadowsocks-csharp\bin\2.0\Release\OtakuSSR.exe
  name: OtakuSSR-2.0.exe
- path: shadowsocks-csharp\bin\4.0\Release\OtakuSSR.exe
  name: OtakuSSR-4.0.exe

