//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Simplified Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Mode=代理模式
        ///No modify system proxy=保持当前设置不变
        ///Disable system proxy=直连
        ///PAC=智能
        ///Global=全局
        ///PAC rule=智能代理配置
        ///Proxy rule=代理规则
        ///Bypass LAN=不代理局域网
        ///Bypass LAN &amp;&amp; China=翻墙出国-不代理局域网+大陆
        ///Bypass LAN &amp;&amp; not China=翻墙回国-不代理局域网+非大陆
        ///User custom=用户自定义
        ///Disable bypass=全局
        ///Servers=服务线路
        ///Servers Subscribe=订阅
        ///Subscribe setting...=订阅设置
        ///Update subscribe SSR node=更新订阅
        ///Update subscribe SSR node(bypass proxy)=更新订阅（不通过代理）
        ///Global settings...=选项设置
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto64_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto64_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo128 {
            get {
                object obj = ResourceManager.GetObject("logo128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo16 {
            get {
                object obj = ResourceManager.GetObject("logo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo20 {
            get {
                object obj = ResourceManager.GetObject("logo20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo32 {
            get {
                object obj = ResourceManager.GetObject("logo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo64 {
            get {
                object obj = ResourceManager.GetObject("logo64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] mgwz_dll {
            get {
                object obj = ResourceManager.GetObject("mgwz_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / 127.0.0.1:__SOCKS_PORT__ .
        ///hide-console
        ///__BYPASS_ACTION__
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] proxy_pac_txt {
            get {
                object obj = ResourceManager.GetObject("proxy_pac_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的本地化字符串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Traditional Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Mode=代理模式
        ///No modify system proxy=保持當前設置不變
        ///Disable system proxy=直連
        ///PAC=智能
        ///Global=全局
        ///PAC rule=智能代理配置
        ///Proxy rule=代理規則
        ///Bypass LAN=不代理區域網路
        ///Bypass LAN &amp;&amp; China=翻墻出國-不代理區域網路和大陸
        ///Bypass LAN &amp;&amp; not China=翻墻回國-不代理區域網路和非大陸
        ///User custom=用戶自定義
        ///Disable bypass=全局
        ///Servers=伺服器線路
        ///Servers Subscribe=訂閱
        ///Subscribe setting...=訂閱設置...
        ///Update subscribe SSR node=更新訂閱
        ///Update subscribe SSR node(bypass proxy)=更新訂閱（不通過代理）
        ///Global settings.. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_tw {
            get {
                return ResourceManager.GetString("zh_tw", resourceCulture);
            }
        }
    }
}
